### ISSUE TITLE
ballcools query not recognizing overlapping positions?

### ISSUE THREAD

**Issue by chooliu** [jksr/ballcools#1]
Hi Wei & Wubin:
  
Thanks so much for developing this package--very stoked about this software.
  
Just seem to be struggling with the `ballcools query` command, where `$mycmeta` was generated via `ballcools meta` on an hg38 fasta reference and `test.allc.tsv.gz` file via `allcools --generate-dataset` using the same genome and chrom sizes reference.

Maybe to reproduce, but wanted to ask if you encountered this error during development or could maybe post examples of 'good' 
.ballc files for comparison as the documentation is developed?

The query command will not output anything without `-w` or `-e` flagged, but showing a single example position for reference:

`less test.allc.tsv.gz | head -n 394 | tail -n 2`
```
chr1    271545  -       CAG     0       1       1
chr1    271547  -       CTC     0       1       1
```

`ballcools a2b test.allc.tsv.gz test.ballc $chromsizes`
`ballcools view -r test.ballc` # seems to works properly and contain the cytosine
`ballcools query test.ballc chr1:-500000 -c $mycmeta -w`

```
Mismatch detected at chr1       271547 between ballc file and meta file.
chr1    271547  ?       C??     0       1       1
```

However: this does appear to be a valid site in the `.cmeta.gz` file: `less $mycmeta | grep '271547'`
```
chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38  271547  -       CTC
```

ballcools installed via conda (.yaml from Github repo version [20d6922](https://github.com/jksr/ballcools/commit/20d69220ff670de4e61c95ca4a32479ab34dc954)) on CentOS Linux 7.
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ballcools                 0.0.3                h2bc3f7f_0    jksr
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.08.22           h06a4308_0  
htslib                    1.18                 h81da01d_0    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
libcurl                   8.3.0                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h516909a_1    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
openssl                   3.1.3                hd590300_0    conda-forge
tabix                     1.11                 hdfd78af_0    bioconda
xz                        5.4.2                h5eee18b_0  
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

Cheers,
Choo

**Comment by jksr** [comment]
Hi Choo,
Thank you for using ballcools. 
Based on your 

`less $mycmeta | grep '271547'`
`chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38  271547  -       CTC`

it seems you are using a vcf file instead of the correct cmeta file?

the cmata file will be a simple tsv with cols of ref, pos, strand, c_context (https://github.com/jksr/ballcools/blob/main/doc/ballc_spec.pdf)

without -e and -w args, `ballcools query` will omit any mismatches between the ballc and cmeta file. I believe that's why it output nothing.

to check the integrity of your ballc data,  you could simply run `ballcools query test.ballc chr1:-500000 ` without providing cmeta `-c`.

it will output the basic cytosine info without stand and context info.

**Comment by chooliu** [comment]
Hm, I see. Not a .vcf: the cmeta file was created by `ballcools meta mygenome.fa mygenome.cmeta`, which generated `mygenome.cmeta.gz` and `mygenome.cmeta.gz.tbi`. I input the .cmeta.gz as the command to the query.

Oops, but I just realized my .fasta has some atypical sequence headers since it's a consortium-specified version: 
```
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

Guess there are three fixes: (1) manually strip annotations .fa headers, (2) just extract the chr, pos, strand, c_context from the resulting cmeta file columns --> remake into tab-separated file, (3) warning/error checking during `ballcools meta` creation if white space / annotations detected in .fa files?

Will give #2 a quick try later this week.

Thanks!
Choo

**Comment by chooliu** [comment]
Just updating to confirm that it was a .fasta annotation issue and not `ballcools query` issue: either option 1 or 2 described above resolves the issue. Thanks Wei! Will keep testing ballc and over the next couple weeks bug you with some feature requests needed for adoption into our lab's pipelines.

```
# Option 1 
cut -d ' ' -f1 whitespace_annotated.fa > headerfixed.fa
ballcools meta headerfix.fa headerfix.cmeta

# Option 2 (way slower)
less  whitespace_annotated.cmeta.gz \
  | awk -F '[[:space:]]+' '{OFS = "\t"} {print $1, $8, $9, $10}' \
  | gzip > headerfixed.cmeta.gz
```

**Comment by jksr** [comment]
thank you @chooliu for the test! It's really helpful

**Comment by jksr** [comment]
fixed in https://github.com/jksr/ballcools/releases/tag/v0.0.5
where only the strings between '>' and the first whitespace (if exists) in a fasta file will be recognized as chrom names.
